### ISSUE TITLE
Stucks on Windows (LoadLangModel)

### ISSUE THREAD

**Issue by bozzyk** [bakwc/JamSpell#62]
Greetings to author!
There is problem with JamSpell on windows.
I got warning with "pip install jamspell":
`C:\Users\bozzy>pip install jamspell`
`Collecting jamspell`
`Using cached`
`https://files.pythonhosted.org/packages/5a/16/0a808e926a835604007066085cb2183b337694a06240a99945b31fa14f27/jamspell-0.0.11.tar.gz`
`Installing collected packages: jamspell`
`Running setup.py install for jamspell ... done`
`Could not find .egg-info directory in install record for jamspell from https://files.pythonhosted.org/packages/5a/16/0a808e926a835604007066085cb2183b337694a06240a99945b31fa14f27/jamspell-0.0.11.tar.gz#sha256=6dcaf1ae631af6c0904f9ba016bf2404e930237eb73e4d471ee92a77327af8f1`
`Successfully installed jamspell`
And then program stucks in "infinite loop" - nothing happens after calling `corrector.LoadLangModel('en.bin')` (from example in readme)
Also python process with jamspell running takes ~9.5 GB from 16 GB RAM.
WAIDW?

**Comment by AndreyLevitsky** [comment]
I'm facing the same issue. Also there is no function `_jamspell.TSpellCorrector_LoadLangModel` in the `_jamspell.py` module.

**Comment by drozado** [comment]
I'm experiencing the same issue

**Comment by yinguoqing123** [comment]
I'm experiencing the same issue, who have resolved this issue?

**Comment by yinguoqing123** [comment]
> Greetings to author!
> There is problem with JamSpell on windows.
> I got warning with "pip install jamspell":
> C:\Users\bozzy>pip install jamspell
> Collecting jamspell
> Using cached
> https://files.pythonhosted.org/packages/5a/16/0a808e926a835604007066085cb2183b337694a06240a99945b31fa14f27/jamspell-0.0.11.tar.gz
> Installing collected packages: jamspell
> Running setup.py install for jamspell ... done
> Could not find .egg-info directory in install record for jamspell from https://files.pythonhosted.org/packages/5a/16/0a808e926a835604007066085cb2183b337694a06240a99945b31fa14f27/jamspell-0.0.11.tar.gz#sha256=6dcaf1ae631af6c0904f9ba016bf2404e930237eb73e4d471ee92a77327af8f1
> Successfully installed jamspell
> And then program stucks in "infinite loop" - nothing happens after calling corrector.LoadLangModel('en.bin') (from example in readme)
> Also python process with jamspell running takes ~9.5 GB from 16 GB RAM.
> WAIDW?

do you solve it? if you do, could you tell how do? thanks

**Comment by jackneil** [comment]
so of note on this issue ... during the first run of any language model (i.e. 'en.bin') a cache file is prepared. This takes approximately 100x the RAM of the .bin file. So that en.bin file being ~60mb means you need about 6gb of RAM to create the cache. 

What you're seeing there is the cache creation process. I've updated the code to give a running progress during the generation process and will push said branch soon. In the meantime just be patient and make sure you have plenty of RAM to generate the cache file (which will have a name like en.bin.spell). Or spin-up a cloud server for this process.
-jack

**Comment by rprilepskiy** [comment]
@jackneil, what's the approximate time of preparing a spell file? Based on your computing power, and file size. 
E.g. having 0.5GB bin -> 50GB RAM (~100X) for *.spell creation -> X time

**Comment by bakwc** [comment]
Fixed in "JamSpellPro". JamSpellPro has a cross-platform models available on windows, mac, linux and mobile devices.
.spell files now included in distributing models, so you don't have to wait on the first run until model is processed.

JamSpellPro is available at [jamspell.com](https://jamspell.com/)
